// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHJvDXqmfCm7lq4JCxtvLz1zTv1M_LrLg',
    appId: '1:469561203988:web:0552338a751b9d4a523601',
    messagingSenderId: '469561203988',
    projectId: 'pear-442e7',
    authDomain: 'pear-442e7.firebaseapp.com',
    databaseURL: 'https://pear-442e7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pear-442e7.appspot.com',
    measurementId: 'G-T8KQWEXYEF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnLl4WdRxfjZ60x_ApAF60UjGy7gObON0',
    appId: '1:469561203988:ios:509a2adaf61f9a9b523601',
    messagingSenderId: '469561203988',
    projectId: 'pear-442e7',
    databaseURL: 'https://pear-442e7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pear-442e7.appspot.com',
    iosClientId: '469561203988-gk8k9af6k7d3dk74o2o8tv26nlbhp5k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pear.RunnerTests',
  );
}
